name: unitree-client
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pinocchio
  - casadi >=3.6,>3.7
  - cyclonedds=0.10.2
  - ipython >=8.34.0
  - mujoco >=3.3.0
  - numpy =1.26.4
  - pyzmq >=26.3.0
  - scipy >=1.15.2
  - websockets >=15.0