name: unitree-client
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pinocchio
  - casadi >=3.7.0
  - ipython >=8.34.0
  - mujoco >=3.2.7
  - numpy =1.26.4
  - pyzmq >=26.3.0
  - scipy >=1.15.2
  - websockets >=15.0