name: Build and Push Docker Images
on:
  push:
  pull_request:
  workflow_dispatch:
permissions:
  id-token: write
  contents: read
  packages: write
env:
  URL: ghcr.io/${{ github.repository }}
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container:
          - path: .devcontainer
            name: dev
          - path: .
            name: server
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.URL }}.${{ matrix.container.name}}
          flavor: |
            latest=true
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=ref,event=tag
            type=sha
      - name: QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: latest
          driver-opts: image=moby/buildkit:latest
      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.container.path }}
          file: ${{ matrix.container.path }}/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          push: true
          pull: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
